### PR TITLE
First cut at switching to new mesos/marathon deployer

### PR DESCRIPTION
**Pull request by trisberg**
Resolves spring-cloud/spring-cloud-dataflow-admin-mesos#23
Resolves spring-cloud/spring-cloud-dataflow-admin-mesos#35
Resolves spring-cloud/spring-cloud-dataflow-admin-mesos#43

### CODE REVIEW

**Comment by trisberg** [comment]
Depends on https://github.com/spring-cloud/spring-cloud-mesos-deployer/pull/1

**Comment by trisberg** [comment]
Defaults to Kafka configs

Added RabbitMQ config for Mesos, use the following to start:

```
curl -X POST http://192.168.33.10:8080/v2/apps -d @rabbitmq.json -H "Content-type: application/json"
```

Used this for Kafka on Mesos - https://github.com/mesos/kafka
with the following kafka-mesos.properties

```
debug=true
user=vagrant
storage=zk:/mesos-kafka-scheduler
master=mesos:5050
zk=mesos:2181/
api=http://192.168.33.10:7000
```

**Comment by jvalkeal** [comment]
I don't have environment to test but code looks good and is exactly what I've been doing on yarn side.

**Comment by trisberg** [comment]
You can follow these instruction to set up a Vagrant VM - https://gist.github.com/trisberg/b3134473c00209ce1b5a

Then use the rabbitmq.json to run with rabbit or follow these instructions to use Kafka - https://github.com/mesos/kafka

**Comment by ericbottard** [comment]
Tried this with rabbitmq and the following 2 apps:

```
module register --name time --type source --uri docker:springcloudstream/time-source-rabbit:latest --force
module register --name log --type sink --uri docker:springcloudstream/log-sink-rabbit:lates
```

The apps do deploy ok (so the use of mesos-deployer is good), but can't connect to rabbit.

Indeed, I think there lacks a whole part of the functionality we had before with the mesos-connector: how do you specify which "services" apps should connect to? And how do we decouple the client consumption of the connection details (in the app) from the part that knows where to connect (I expect at least the deployer to use the marathon API to discover exposed ports, etc).

**Comment by trisberg** [comment]
We haven't defined how service discovery should work with the new deployer so we are punting on this for now. You can provide the connection parameters using env vars for the server for now:

```
spring:
  cloud:
    deployer:
      mesos:
        marathon:
          environmentVariables: 'SPRING_RABBITMQ_HOST=192.168.33.10,SPRING_RABBITMQ_PORT=31193'
```

**Comment by ericbottard** [comment]
Rebased and meged as fa5bbde

**Pull request closed without merging**
